#!/usr/bin/env python3
"""Render the rule tables and reference page from the registry.

WHY THIS EXISTS
---------------
Rule tables drifted from the implementation repeatedly: a rule added without a
README row, a row whose severity no longer matched, a hand-maintained total
that stopped adding up. Three separate tests existed to catch that by hand, and
every one of them fired during 0.17.0 development.

Generation replaces detection. ``--check`` exits non-zero when the committed
docs no longer match ``o1js_scan/rules.py``, so a rule cannot be added without
the docs following.

    python3 scripts/render_rule_docs.py            # rewrite the generated blocks
    python3 scripts/render_rule_docs.py --check    # verify, change nothing
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT))

from o1js_scan.rules import BACKENDS, specs_for_backend  # noqa: E402

README = REPO_ROOT / "README.md"
RULES_DOC = REPO_ROOT / "docs" / "rules.md"

BEGIN = "<!-- BEGIN GENERATED {name} -->"
END = "<!-- END GENERATED {name} -->"


def _table(backend: str) -> str:
    lines = ["| Rule | Severity | What it means |", "|------|----------|---------------|"]
    for spec in specs_for_backend(backend):
        lines.append(
            f"| `{spec.rule_id}` | {spec.severity_label} | {spec.description} |"
        )
    return "\n".join(lines)


def _summary() -> str:
    header = "| Backend | Rules | High-capable | Medium-capable | Low-capable |"
    lines = [header, "|---------|------:|-------------:|---------------:|------------:|"]
    totals = [0, 0, 0, 0]
    for backend in BACKENDS:
        specs = specs_for_backend(backend)
        counts = [
            len(specs),
            sum("high" in s.severities for s in specs),
            sum("medium" in s.severities for s in specs),
            sum("low" in s.severities for s in specs),
        ]
        label = "o1js" if backend == "o1js" else "Noir"
        lines.append(
            f"| {label} | {counts[0]} | {counts[1]} | {counts[2]} | {counts[3]} |"
        )
        totals = [t + c for t, c in zip(totals, counts)]
    lines.append(
        "| **Total** | **{0}** | **{1}** | **{2}** | **{3}** |".format(*totals)
    )
    return "\n".join(lines)


def _rules_doc() -> str:
    """A stable anchor per rule, so SARIF helpUri can point at one rule."""
    out = [
        "# Rule reference",
        "",
        "<!-- Generated by scripts/render_rule_docs.py. Do not edit by hand. -->",
        "",
        "Every rule `o1js-scan` can emit, with the severities it uses. SARIF",
        "`helpUri` values point at the headings on this page, so they stay stable",
        "as the README is reorganised.",
        "",
        "Where a rule has a non-obvious boundary — a shape it deliberately does",
        "not match, or corroboration it demands before firing — a *Where it",
        "stops* line records it. Those lines are only on this page; the README",
        "table stays one row per rule.",
        "",
    ]
    for backend in BACKENDS:
        label = "o1js / Mina zkApps" if backend == "o1js" else "Noir / Aztec circuits"
        out += [f"## {label}", ""]
        for spec in specs_for_backend(backend):
            out += [
                f"### {spec.rule_id}",
                "",
                f"**{spec.title}** — severity: {spec.severity_label}"
                + (f" — origin: {spec.origin}" if spec.origin else ""),
                "",
                spec.description,
                "",
            ]
            if spec.limitations:
                out += [f"*Where it stops:* {spec.limitations}", ""]
    return "\n".join(out)


def _replace_block(text: str, name: str, body: str) -> str:
    begin, end = BEGIN.format(name=name), END.format(name=name)
    pattern = re.compile(
        re.escape(begin) + r".*?" + re.escape(end), re.S
    )
    if not pattern.search(text):
        raise SystemExit(f"error: README is missing the {name} markers")
    return pattern.sub(f"{begin}\n{body}\n{end}", text)


def render() -> dict:
    readme = README.read_text(encoding="utf-8")
    readme = _replace_block(readme, "O1JS RULE TABLE", _table("o1js"))
    readme = _replace_block(readme, "NOIR RULE TABLE", _table("noir"))
    readme = _replace_block(readme, "RULE SUMMARY", _summary())
    return {README: readme, RULES_DOC: _rules_doc()}


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true",
                    help="verify the committed docs match the registry")
    args = ap.parse_args()

    rendered = render()
    if not args.check:
        for path, body in rendered.items():
            path.write_text(body, encoding="utf-8")
            print(f"  wrote {path.relative_to(REPO_ROOT)}")
        return 0

    stale = [
        path.relative_to(REPO_ROOT)
        for path, body in rendered.items()
        if not path.is_file() or path.read_text(encoding="utf-8") != body
    ]
    if stale:
        print("rule docs are stale: " + ", ".join(str(p) for p in stale), file=sys.stderr)
        print("regenerate with: python3 scripts/render_rule_docs.py", file=sys.stderr)
        return 1
    print(f"rule docs match the registry ({sum(len(specs_for_backend(b)) for b in BACKENDS)} rules)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
